services:
  - type: web
    name: softskilia-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app --chdir backend
    env: python
    region: oregon
    plan: free
    branch: main
